package templates

// RouterTemplateStr   生成router模板
const RouterTemplateStr = `// Code generated by gin-generator. DO NOT EDIT.
// Code generated by gin-generator. DO NOT EDIT.
// Code generated by gin-generator. DO NOT EDIT.     
// 	   ######   #### ##    ##          ######   ######## ##    ## ######## ########     ###    ########  #######  ######## 
//    ##    ##   ##  ###   ##         ##    ##  ##       ###   ## ##       ##     ##   ## ##      ##    ##     ## ##     ##
//    ##         ##  ####  ##         ##        ##       ####  ## ##       ##     ##  ##   ##     ##    ##     ## ##     ##
//    ##   ####  ##  ## ## ## ####### ##   #### ######   ## ## ## ######   ########  ##     ##    ##    ##     ## ######## 
//    ##    ##   ##  ##  ####         ##    ##  ##       ##  #### ##       ##   ##   #########    ##    ##     ## ##   ##  
//    ##    ##   ##  ##   ###         ##    ##  ##       ##   ### ##       ##    ##  ##     ##    ##    ##     ## ##    ## 
//     ######   #### ##    ##         ######   ######## ##    ## ######## ##     ## ##     ##    ##     #######  ##     ##
//
//	Author: Eddy 527084800
// Package router 
package router

import (
	"github.com/gin-gonic/gin"
)
var 
(
{{- range .}}
  {{ .LowerCamelName }}Router *gin.RouterGroup
{{- end }}
)
func InitAutoRouters(r *gin.Engine) {
{{- range .}}	
	{{ .LowerCamelName }}Router = r.Group("/{{ .LowerCamelName }}")
	{{ .LowerCamelName }}Router.GET("/list", controllers.Get{{ .UpperCamelName }}List)
	{{ .LowerCamelName }}Router.POST("/create", controllers.Create{{ .UpperCamelName }})
	{{ .LowerCamelName }}Router.POST("/update", controllers.Update{{ .UpperCamelName }})
	{{ .LowerCamelName }}Router.POST("/delete", controllers.Delete{{ .UpperCamelName }})
	// {{ .LowerCamelName }}Router END !!
{{- end }}	
}

`
